FROM nginx:latest

# RUN mkdir /app && \
#     mkdir /img && \
#     chmod 775 /usr/share/nginx/html/

# COPY html /home/sando

# COPY nginx.conf /etc/nginx/nginx.conf
# COPY default.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
